USE [TPBaseDeDatos]
GO

/****** Object:  Table [dbo].[datos_staging]    Script Date: 03/10/2023 16:18:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[datos_staging](
	[equipoOP_ciudad] [varchar](300) NULL,
	[equipoOP_codigo] [varchar](30) NULL,
	[equipoOP_sigla] [varchar](5) NULL,
	[equipoOP_conferencia] [varchar](20) NULL,
	[equipoOP_division] [varchar](20) NULL,
	[equipoOP_id] [int] NULL,
	[equipoOP_nombre] [varchar](300) NULL,
	[stat_asistencias_id] [int] NULL,
	[stat_asistencias_nombre] [varchar](50) NULL,
	[stat_asistencias_valor] [int] NULL,
	[stat_bloqueos_id] [int] NULL,
	[stat_bloqueos_nombre] [varchar](50) NULL,
	[stat_bloqueos_valor] [int] NULL,
	[equipo_ciudad] [varchar](300) NULL,
	[jugador_codigo] [varchar](40) NULL,
	[pais] [varchar](300) NULL,
	[stat_rebotes_defensivos_id] [int] NULL,
	[stat_rebotes_defensivos_nombre] [varchar](50) NULL,
	[stat_rebotes_defensivos_valor] [int] NULL,
	[equipo_sigla] [varchar](5) NULL,
	[equipo_conferencia] [varchar](20) NULL,
	[nombre_completo] [varchar](1000) NULL,
	[equipo_division] [varchar](20) NULL,
	[draft_year] [int] NULL,
	[fecha] [datetime] NULL,
	[stat_tiros_intentos_id] [int] NULL,
	[stat_tiros_intentos_nombre] [varchar](50) NULL,
	[stat_tiros_intentos_valor] [int] NULL,
	[stat_tiros_convertidos_id] [int] NULL,
	[stat_tiros_convertidos_nombre] [varchar](50) NULL,
	[stat_tiros_convertidos_valor] [int] NULL,
	[tiros_porcentaje] [decimal](5, 2) NULL,
	[nombre] [varchar](300) NULL,
	[stat_faltas_id] [int] NULL,
	[stat_faltas_nombre] [varchar](50) NULL,
	[stat_faltas_valor] [int] NULL,
	[stat_tiros_libres_intentos_id] [int] NULL,
	[stat_tiros_libres_intentos_nombre] [varchar](50) NULL,
	[stat_tiros_libres_intentos_valor] [int] NULL,
	[stat_tiros_libres_convertidos_id] [int] NULL,
	[stat_tiros_libres_convertidos_nombre] [varchar](50) NULL,
	[stat_tiros_libres_convertidos_valor] [int] NULL,
	[tiros_libres_porcentaje] [decimal](5, 2) NULL,
	[partido_id] [int] NULL,
	[altura] [varchar](200) NULL,
	[esLocal] [varchar](20) NULL,
	[caminseta] [varchar](300) NULL,
	[apellido] [varchar](300) NULL,
	[stat_minutos_id] [int] NULL,
	[stat_minutos_nombre] [varchar](50) NULL,
	[stat_minutos_valor] [int] NULL,
	[equipo_nombre] [varchar](300) NULL,
	[stat_rebotes_ofensivos_id] [int] NULL,
	[stat_rebotes_ofensivos_nombre] [varchar](50) NULL,
	[stat_rebotes_ofensivos_valor] [int] NULL,
	[equipoOP_puntos] [int] NULL,
	[jugador_id] [int] NULL,
	[stat_puntos_id] [int] NULL,
	[stat_puntos_nombre] [varchar](50) NULL,
	[stat_puntos_valor] [int] NULL,
	[posicion] [varchar](5) NULL,
	[rebotes] [int] NULL,
	[temporada_id] [int] NULL,
	[stat_segundos_id] [int] NULL,
	[stat_segundos_nombre] [varchar](50) NULL,
	[stat_segundos_valor] [int] NULL,
	[stat_robos_id] [int] NULL,
	[stat_robos_nombre] [varchar](50) NULL,
	[stat_robos_valor] [int] NULL,
	[equipo_codigo] [varchar](30) NULL,
	[equipo_puntos] [int] NULL,
	[equipo_id] [int] NULL,
	[stat_tiros_triples_intentos_id] [int] NULL,
	[stat_tiros_triples_intentos_nombre] [varchar](50) NULL,
	[stat_tiros_triples_intentos_valor] [int] NULL,
	[stat_tiros_triples_convertidos_id] [int] NULL,
	[stat_tiros_triples_convertidos_nombre] [varchar](50) NULL,
	[stat_tiros_triples_convertidos_valor] [int] NULL,
	[tiros_triples_porcentaje] [decimal](5, 2) NULL,
	[stat_perdidas_id] [int] NULL,
	[stat_perdidas_nombre] [varchar](50) NULL,
	[stat_perdidas_valor] [int] NULL,
	[peso] [varchar](300) NULL,
	[resultado] [varchar](10) NULL,
	[temporada_descripcion] [varchar](20) NULL,
	[idPais] [int] NULL,
	[equipo_idCiudad] [int] NULL,
	[equipoOP_idCiudad] [int] NULL
) ON [PRIMARY]
GO


